name: Publish Files to Local Server

on:
  push:
    branches:
      - main

jobs:
  publish-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Permissions for SSH Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create logos folder
        run: ssh -o StrictHostKeyChecking=no gzl10g@10.0.4.100 'mkdir -p /share/Web/logos'
       
      - name: Copy Files to Remote Server
        run: scp -o StrictHostKeyChecking=no -r * gzl10g@10.0.4.100:/share/Web
